more work

diff --git a/src/wg-broker-server b/src/wg-broker-server
--- a/src/wg-broker-server
+++ b/src/wg-broker-server
@@ -37,38 +37,31 @@ cleanup() {
 trap cleanup exit
 
 get_wg_peers() {
-    $WG show ${nic_name} | grep peer |sed 's/peer://g' | tr '\n' ' '
+  $WG show ${nic_name} | grep peer |sed 's/peer://g' | tr '\n' ' '
 }
 
 get_connection_count() {
-    peers=( $(get_wg_peers) )
-    echo ${#peers[@]}
+  peers=( $(get_wg_peers) )
+  echo ${#peers[@]}
 }
 
 add_interface() {
-    local newdevice="${nic_name}"
+  local newdevice="${nic_name}"
 
-    unset INACTIVE[$newdevice]
+  unset INACTIVE[$newdevice]
 
-    ip link add dev $newdevice type wireguard
-    ip link set multicast on mtu $MTU dev $newdevice
-    devicenumber=${ifname##*-}
-    ip a a fe80::$devicenumber/64 dev $newdevice
+  ip link add dev $newdevice type wireguard
+  ip link set multicast on mtu $MTU dev $newdevice
+  devicenumber=${ifname##*-}
+  ip a a fe80::$devicenumber/64 dev $newdevice
 
-    # ip6tables -A INPUT -i $newdevice -p udp --dport 6696 -j ACCEPT
-    # ip6tables -A INPUT -i $WAN -p udp --dport $freeport -j ACCEPT
-    # iptables -A INPUT -i $WAN -p udp --dport $freeport -j ACCEPT
-    ip link set up dev $newdevice
-    echo add_meshif "$1" | socat - unix:$L3ROAMDSOCK
-    echo add_meshif "$1" | socat - unix:$MMFDSOCK
-    echo interface $newdevice | timeout 0.2 nc ::1 $BABELPORT >/dev/null
-}
-
-add_peer() {
-    local public_key="$1"
-    unset INACTIVE[$public_key]
-
-    $WG set ${nic_name} private-key $PRIVATEKEY listen-port $WIREGUARDPORT peer $public_key allowed-ips ::/0
+  # ip6tables -A INPUT -i $newdevice -p udp --dport 6696 -j ACCEPT
+  # ip6tables -A INPUT -i $WAN -p udp --dport $freeport -j ACCEPT
+  # iptables -A INPUT -i $WAN -p udp --dport $freeport -j ACCEPT
+  ip link set up dev $newdevice
+  echo add_meshif "$1" | socat - unix:$L3ROAMDSOCK
+  echo add_meshif "$1" | socat - unix:$MMFDSOCK
+  echo interface $newdevice | timeout 0.2 nc ::1 $BABELPORT >/dev/null
 }
 
 del_interface() {
@@ -81,61 +74,70 @@ del_interface() {
   } >&2
 }
 
+add_peer() {
+  local public_key="$1"
+  unset INACTIVE[$public_key]
+
+  $WG set ${nic_name} private-key $PRIVATEKEY listen-port $WIREGUARDPORT peer $public_key allowed-ips ::/0
+}
+
 del_peer () {
-    local peer="$1"
-    $WG ${nic_name} set peer $peer remove 
+  local peer="$1"
+  $WG ${nic_name} set peer $peer remove 
 }
 
 prune_peers() {
-    local lines=$WG show ${nic_name} latest-handshakes
-    for line in "${lines[@]}"; do
-        read -a strarr <<< "$line"
-        peer="${strarr[0]}"
-        lhandshake="${strarr[1]}"
-        age=$(($(date +%s)-lhandshake))
-        if  (( (lhandshake > 0 && age > 600) || (lhandshake == 0 && "${INACTIVE[$peer]:-0}" == 1) ))
-        then
-        del_peer $peer
-        return
-        elif [[ $((lhandshake)) -eq 0 ]] && [[ -z ${INACTIVE[$peer]} ]]
-        then
-            INACTIVE[$peer]=1
-        fi
-    done
+  local lines=$WG show ${nic_name} latest-handshakes
+  for line in "${lines[@]}"; do
+    read -a strarr <<< "$line"
+    peer="${strarr[0]}"
+    lhandshake="${strarr[1]}"
+    age=$(($(date +%s)-lhandshake))
+    if  (( (lhandshake > 0 && age > 600) || (lhandshake == 0 && "${INACTIVE[$peer]:-0}" == 1) ))
+    then
+      del_peer $peer
+      return
+    elif [[ $((lhandshake)) -eq 0 ]] && [[ -z ${INACTIVE[$peer]} ]]
+    then
+      INACTIVE[$peer]=1
+    fi
+  done
 }
 
 handle_connection() {
-    family=$1
-    read -r REPLY
+  family=$1
+  read -r REPLY
 
-    local pkey=$(jq -r ".pubkey" <<<"$REPLY")
+  local pkey=$(jq -r ".pubkey" <<<"$REPLY")
 
-    if [[ -n $pkey ]]
-    then
-	if [[ ! $(base64 -d <<<"$pkey" 2>/dev/null |wc -c) -eq 32 ]]
-	then
-	    echo "invalid public key" >&2
-	    return
-	fi
+  # TODO this block looks wonky
+  if [[ -n $pkey ]]
+  then
+  
+  if [[ ! $(base64 -d <<<"$pkey" 2>/dev/null |wc -c) -eq 32 ]]
+  then
+    echo "invalid public key" >&2
+    return
+  fi
 
-	ifname=${nic_name}
-    port=${WIREGUARDPORT}
+  ifname=${nic_name}
+  port=${WIREGUARDPORT}
 
-	success=0
-	[[ $(get_connection_count) -gt $MAXCONNECTIONS ]]
-	then
-	    response="{\"version\":1, \"error\": { \"code\":1, \"reason\":  \"Remote peer is not accepting additional connections\"} }"
-	else
-	    response="{\"version\":1, \"port\": $port, \"time\": $(date +%s) }"
-	    success=1
-	fi
+  success=0
+  [[ $(get_connection_count) -gt $MAXCONNECTIONS ]]
+  then
+    response="{\"version\":1, \"error\": { \"code\":1, \"reason\":  \"Remote peer is not accepting additional connections\"} }"
+  else
+    response="{\"version\":1, \"port\": $port, \"time\": $(date +%s) }"
+    success=1
+  fi
 
-	echo "working on $ifname, write to peer: $response" >&2
-	# del_interface "$ifname"
+  echo "working on $ifname, write to peer: $response" >&2
+  # del_interface "$ifname"
 
-	[[ "$success" == "1" ]] && add_peer "$pkey"
-	echo "$response"
-    fi
+  [[ "$success" == "1" ]] && add_peer "$pkey"
+    echo "$response"
+  fi
 }
 
 allow_udp_on_wg_interfaces() {
@@ -151,7 +153,7 @@ add_interface
 iptables -nL -v|grep dpt:$BROKERPORT|grep tcp|grep $WAN |grep -q ACCEPT || iptables -A INPUT -i $WAN -p tcp --dport $BROKERPORT -j ACCEPT
 ip6tables -nL -v|grep dpt:$BROKERPORT|grep tcp|grep $WAN |grep -q ACCEPT || ip6tables -A INPUT -i $WAN -p tcp --dport $BROKERPORT -j ACCEPT
 iptables -nL -v|grep udp |grep $WAN|grep $WIREGUARDPORT -q || iptables -A INPUT -i $WAN -p udp -m multiport --dports $WIREGUARDPORT -j ACCEPT
-ip6tables -nL -v|grep udp |grep ${WAN}|grep $WIREGUARDPORT -q || ip6tables -A INPUT -i $WAN -p udp -m multiport --dports $WIREGUARDPORT -j ACCEPT
+ip6tables -nL -v|grep udp |grep $WAN|grep $WIREGUARDPORT -q || ip6tables -A INPUT -i $WAN -p udp -m multiport --dports $WIREGUARDPORT -j ACCEPT
 
 # allow babeld, l3roamd and mmfd on wireguard interfaces
 allow_udp_on_wg_interfaces 5523
@@ -167,22 +169,22 @@ rm -f "/var/lock/${0##*/}"
 {
 while [[ -z $EXITING ]]
 do
-    prune_peers
-    sleep 300
+  prune_peers
+  sleep 300
 done
 } &
 
 {
 while [[ -z $EXITING ]]
 do
-    cat /tmp/wg-broker6 | handle_connection 6 | nc -6 -w 1 -l $BROKERPORT > /tmp/wg-broker6
+  cat /tmp/wg-broker6 | handle_connection 6 | nc -6 -w 1 -l $BROKERPORT > /tmp/wg-broker6
 done
 } &
 
 {
 while [[ -z $EXITING ]]
 do
-    cat /tmp/wg-broker4 | handle_connection 4 | nc -4 -w 1 -l $BROKERPORT > /tmp/wg-broker4
+  cat /tmp/wg-broker4 | handle_connection 4 | nc -4 -w 1 -l $BROKERPORT > /tmp/wg-broker4
 done
 } &
 
